### ISSUE TITLE
To string method

### ISSUE THREAD

**Issue by conjectwan** [easyrdf/easyrdf#233] opened 2015-01-26 13:13 UTC
Hello,

If we need to have a human-readable version of a resource, we pass by the __toString method.

I'm asking myself about the pertinence to return the resource uri. Indeed, the uri is not very human-readable. That would not be preferable to return a rdfs:label if it is defined ?

Thank you in advance.

**Comment by njh** [comment] 2015-01-26 13:22
Good point.

There is a ->label() method that does this, and falls back to other properties if no rdfs:label is available.

**Comment by erwanastro** [comment] 2015-01-26 13:44
Thank you for your response. The problem is that today, we use a tierce library that casts an object into a string. So we can not pass by an other function that __toString or profit of the label function in this case.

**Comment by k00ni** [comment] 2020-07-23 13:32
Is there anything to add here? If not, we should close this issue and mark it as "wont-fix".

**Comment by njh** [comment] 2020-07-23 23:26
Yeah, I think that `__toString()` has been returning URIs for so long, that it is likely that people depend upon that behaviour.

@conjectwan sorry, this was a very long time ago, so you have probably moved on, but you could subclass EasyRdf\Resource and then change the default class for resources using `EasyRdf\TypeMapper\setDefaultResourceClass()`.

**Closed by njh** 2020-07-23 23:26 UTC
